import {
  verifyFirstLetter,
  verifyRequiredField,
  verifyMaxLength,
  verifyWebsite,
} from "../../utils";
import { ERROR_TEXT, TEXTAREA_MAX_LENGTH } from "./constants";

const REQUIRED_FIELD_VALIDATOR = {
  validator: verifyRequiredField,
  errorText: ERROR_TEXT.fieldIsEmpty,
};

const UPPERCASE_CHAR_VALIDATOR = {
  validator: verifyFirstLetter,
  errorText: ERROR_TEXT.fieldShouldBeginUpperLetter,
};

const TEXTAREA_MAX_LENGTH_VALIDATOR = {
  validator: (value) => verifyMaxLength(value, TEXTAREA_MAX_LENGTH),
  errorText: ERROR_TEXT.textLimitExeeded,
};

const WEBSITE_URL_VALIDATOR = {
  validator: verifyWebsite,
  errorText: ERROR_TEXT.websiteIncorrectUrl,
};

const NAME_VALIDATORS = [REQUIRED_FIELD_VALIDATOR, UPPERCASE_CHAR_VALIDATOR];
const SURNAME_VALIDATORS = [REQUIRED_FIELD_VALIDATOR, UPPERCASE_CHAR_VALIDATOR];
const PHONE_VALIDATORS = [REQUIRED_FIELD_VALIDATOR];
const DATE_OF_BIRTH_VALIDATORS = [REQUIRED_FIELD_VALIDATOR];
const WEBSITE_VALIDATORS = [REQUIRED_FIELD_VALIDATOR, WEBSITE_URL_VALIDATOR];
const ABOUT_ME_VALIDATORS = [
  REQUIRED_FIELD_VALIDATOR,
  TEXTAREA_MAX_LENGTH_VALIDATOR,
];
const STACK_VALIDATORS = [
  REQUIRED_FIELD_VALIDATOR,
  TEXTAREA_MAX_LENGTH_VALIDATOR,
];
const PROJECT_INFO_VALIDATORS = [
  REQUIRED_FIELD_VALIDATOR,
  TEXTAREA_MAX_LENGTH_VALIDATOR,
];

export {
  NAME_VALIDATORS,
  SURNAME_VALIDATORS,
  PHONE_VALIDATORS,
  WEBSITE_VALIDATORS,
  ABOUT_ME_VALIDATORS,
  STACK_VALIDATORS,
  PROJECT_INFO_VALIDATORS,
  DATE_OF_BIRTH_VALIDATORS,
};
